apiVersion: v1
kind: Service
metadata:
  name: umami
  namespace: platform
  labels:
    app: umami
    component: analytics
spec:
  selector:
    app: umami
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
