---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shared-pg-superuser
  namespace: data
spec:
  encryptedData:
    password: AgAQMuhE90XDfsR6sYVYUfzRBKMk0SSuKNG83THiqoilpLTcm2A8BX/f8FsimG/PGrjmSW+7hvizjNfeNjQYXfxSAg+Q1+kT8VK6YbNn3AeiCRcCxqTQR63qgVypkVv5ehzlH7G5soxUvxpOjiqkraoxiEzSaOHTOcnJF6TPL9TZmcGH7NwM1r/ZZfhO8GdIpvWAP2oMu0nhriLr+4jxs8rcnx+9wxWZhHf0H/Yp777GHwj2axBNfIzmz48WjwHOCkOnUm9AioA05JtmesMW5383u3YCzXPHLnkRTdPOBIJlSS8DSgvRhjc4RemDLlsRXpZHl7xJKW3UdZlggpIgFt6tNmbVUFjPrSpAmWIKswhoGQtknvMzWP8QCz2yAJW621M/ldLyGCq+6rEW0aTludkwkiAMFMBvzF43YhES4VICsOJfnPawcZ5dhlhvLGugEULccEa18M1RMO8x5jINPEgzSNQkOlLFr4fzOdU603QTrxZjiaXDeeYsKPD2EaEoXalWufAfqUvih79A4wwJeDDEatkUEW1p6CXRjCspp9T6hiyoMlAtCnjTV920Hzo9n3S8JgAY9tn/UgTmOJTnYYb5Ltbmt9zW3p7ABsQR6xQBxtarzgFG6DA3pzri5FSAOR/eBSWwFQ18hagvgankAGVpWdDfTyR9FFyARi/y+lRFjOXapPUHzaJvgRCssJjDssD0mgo+LLETqnFShUjnhAeB3vrzEgCxBkjFgqVE9ajfTAIyb3tA7f21afKtrg==
    username: AgBieYHZ/qHoh0S4xU6xHpXcvYUFdQx5QNV6/DjRN7vCHcC3JlG7oYXQ/B6UiWOUVp7c9dtJwkbfqA+rIIto70J3C/B9sw8EjYEQHS2D+xI4c7HeiRgwOUzdhqgbE9bXpGY0CNa24jsgCQIHq5aL/wZuOOvkqtMN4pk4EH+ho83GzFco6Z0H7CL/dV9qPXe6qYNsnMOMqVnUjsPoSrGQOljlPS4m6oqrG9GJHXb+aJillwo1fGItBMUsYASpT4Tdc1s5d3jcMB4o35Qi7Luzec2Yi1vVofRCk3srDQezvc7mqB9t16TFz/hyJiLy7u/DKyMfnUh/pxmmMeEP480pz2AoMIb7zldyfI70dWmEYj2HtZ6fE2/fUPJJvqGwYO9BB4ooO+J9PVdF/BVbsiCGX1aHQsRCbU0JYOFob8nkxBq1YKyuutZ2afggxknoXvhqMJVsBg+92eX6EX17uwAd4MN7tSjYGzYXARQiAsooW0yKPiYNWk5Ix8JmleQsuTJzT/bOU8NS2W/6e/Znd08Ih2nrBRRs0a8n3oTZVNrC1u//iGrxhvkmpcN5+9DHhi7BvvjYJdva163uXtRoKypsaMMUlu8S6bycCa4MuNgaiOAZjt3zDflslnc+tkzzwsfi1qsP3a9RsVmExYNAuik/T6mut28+dx9+muyRj8Ngi4hQq9MocojrZWtZgQFIOuWehHM06OG66ZnJ/A==
  template:
    metadata:
      name: shared-pg-superuser
      namespace: data
    type: kubernetes.io/basic-auth
