---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zot-s3-credentials
  namespace: platform
spec:
  encryptedData:
    access-key: AgAhZ0MjqvezAg0Vh4S1AMphqRtOFs/e2C/qZbb0QGpFmtIXJl9t5IrnyKADjdZvbdkiMqnjPRRTYFyySJ7BkEpqNqdWiNRVSFxmlNvmcYIkDB7DyvwHQ1tl3lUWVqy/zJQRfesFi+2/WzwbjEF5qGaRD8/g3dHDqGRLwwS4SHYkPgX9pTo+PqBMHjUvdFdb2Alu41SRWN7BBJ0VU8DIsF+8iDINRYwMls6muPUt3v4dyqJwghNaqgJaj1+BA9FvYwFL/2H6Z9q/MGnePi1Bsx28XwzR7CcKE4BlXWklboV8c/4wWelJP6gPf5fzT6Iaaw9hGEWIHKrrLZsKkJ559T2kxmw5BayZVFkXLCeP0DS4mPAP8a0H0/zMfxQWESYWiscr7vo+gjG4SLOMZI+1z9yq0iZx4NOT1UMiP2OmeZzszDerQ4sLfspCS+j+F/uHze3GPdtqMe2zRX4TtMMz7soFOl9CFX1Z1RuJLNhle7N1a287PSOuaukeblNhdt4iuO8ZkmuURHGFliSy1XqMXHRTsKGN6Wzc4mK8Cz3QfHqWjCsn+i6lYNELyB7TqwBLzDRioHg8hNDvx+3Sa0nYaTgLIcyqth14ZTBNC5Aivc3yVIIagQY6h3lNwYYswn1oRyDabQ/dZYkf+15HNREavXJh8JgNqCViQ2qOCYDg+c82cf0Ip5L3ol4HQoABAaKCexnnf1eSLTyRKf5TU0Z1kJy9Vs3ZDA==
    secret-key: AgAy7xR7mG/ubTApglFEi8DzvvqqaB8m+LiVzUtfnHZfRRg48xtkNvl3ga1uXI90XudYmOWvmUP82eioMf9ag0VHKMQgv1Q3qw1oYdJfxZpFaLOzN3A797Nvlau5FBUPGFxeu9kyNlcR4hR2VNC9mpSJZyGAnYqvR1sKS2JNCit1IUvZYFsS8Lt8ji0/X/DYLl1a/Q+6J1JfZKfE5lUzgN/pwg2S666jOnM2yru/SnSsSE2m2HnzeZKkUm2g3K5C5N5uN5nH5Td2BW65FXvYucEAwdfMBLbo/uSDhQMQNlXgR4c+S8JVHBQULJG8JbahV6OwgSJKRUt/LNZq2triMUy7c7/aLeA/Z6QUq0be/CUUrZSfAw0SgKXUq3aaUwxfhTteixC/DiqOrOZZIRPGCxwQ621eH4/oSWsx+Q1nzuxyNELmvw5O/yzwX0PVlUJEBQOYP3HiM3Hd5k2pj/1n9wHSFuilJFoaPaRNlCwYC4Q7GbqLuCooPcF2FFKpI8n7e5aKiPjSNArt6iy/MWLfJ/GnU1ucK5b6mPjhVHhh62OALv4dOR/pF+eAK4Xxb78MRKIiJZ9KP1lJ2VWBy2JLngTlUfgNivg0gZaknLf7Mg+I6CA+qluJ1p+Ov4Wm7H1NwdUWjuVN+kJz1AUFK8Jq/JtBG6kFB3uuyxV6oEmcWB6PaYm4x6q6wDbTjeYblnZeebS/XtX2VlUF9lPhNukoItvAueZcG+7q6ZfHJPlGpTEBxU3C1isB2yqg
  template:
    metadata:
      name: zot-s3-credentials
      namespace: platform
    type: Opaque
