---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zot-registry-auth
  namespace: platform
spec:
  encryptedData:
    password: AgANygEsdTDGDevtxcC9vgJfwB2G6l1OPOdmWDCcEY/CaG8f4d+FhXfiqXI1ULcEzv1F+Qt90EOarAej4xtzIhYB3tmdj1Khj9hAj+wBSykhIwrD+EiBvUtE1GFaGBJyR+05ht7qn6cH1/sajR1vqTGRIdMCzWLpJqZUTC0T8ho2jRTiJIArZBWWzSfTVMosFNDejdC2m7ycvbMqJNAFQn5J7FiTpxhhU7rLiAcvcwENch2hDCuBwZYsqTRTyeZoWv+wSWmvn1Cpgf9WsbeDsISPtvlhe2qk7FrdU6gdsFP0IiSvXKNMVQKB5KqJXwKMSiG9RXdnatkGEVZR5UxBPVF6RiWOkjRSX//k1Af8mbgx6/UGK+cSTIv6mxiuYqoDRC/+z+RWcaq9Iq8aJs5J901E8jYgsb5NvdwgnRj3AML1aBZncOeMRWv4ADHTmHKY6NoQNkQpPkyrAJrJN0IEHe73dp0FzKubTiNQDd13tgoKV4B1ZK0wNaciyyvfm40Ssn4MkT2Mja6N8ZdcUWJUmI74eRnmnGG2/rSGzuakpERO6Q7ebA2PAo+pHO8FhenLl44az76zYkWKKPGRxdUiUhlgky+/jF4GwPmDzrhO9JGnP12zNB0psSGBd2yJAgGE7Ekj6dOoHSaKPVgF5QIv8CnojrNijem+Cd3B/HuWkUfgyEFLk3/uNnYSOiPYhO0UKIabHYq1LuSCsR0tifnVqa6Z+5c9fr8iYabrfU0uOIUIORVV5Ecp0Q2aDgf6OQ==
    username: AgBz/lK7CKv/D9KIVXQO4Wig6WpPa/ZNIyH01IxHxBgOJngQc74ZaaH3Wb/jFMXlmEQCjCOJCmK20hwLJ2B4G+RmHZZ9ie/qXfpuF2vI4qwmnPRtlOSOmrHSzHECuh3LodnVmhVaZ7VlAhZ5nzIBNstcr+7rYRAkA6nOM18M0lQ0mjgeqYpabMuzOxYBnJ3AMoZnO+qoId3rTVRwc8qn4PgGn3MoT7zq+BWI8FT5dDJhdW6jdyG/i1zibx5EVoMXZMAbe80wd/RR2bABKnPGXhFoA5lLNseXEbIlLq+RJZ7gJ1gqxOLrijUBSClJ91y6n/O0qj6fTfG1EggQpRcbw9F6njhKSg+yHIR2sR5bjmEMfEAvZdShs4gnWTb18XYVhc2jOa8Y/a7F/RltTJn7Tj5i4gZI0bHaIYCHkDvwapPw4JPFbkG5a3+26lxydnIQXSN6q/esoQpfaW4v0PHgxwrWqqa4o/8p5uZ3+d/S3b29lax9tpty7ZqiuhCYT8ipW4Hl9h9TpkuQJ8mmwtvPDLmV2eEdEpKFaDLCb5gDpnHJo3zbYVHQzPSe4eL0DmCEH+KeUihZPHl/Ls7GMNuYPa8AQoD5U3x4VgWI4INt0CE68CI/sl4SQc5zz0xkHUMFv9G/9s0VslC3VYnwtHjsQ4kp0yBjtRh8fDBx+xhspFoBYXnXdF/554rAAi847Rn6ZKexPMH+yg==
  template:
    metadata:
      name: zot-registry-auth
      namespace: platform
    type: kubernetes.io/basic-auth
